---
- name: Installing and launching filebeat
  hosts: webservers
  become: yes
  tasks:
  - name: Download filebeat
    copy:
      src: filebeat-7.4.0-amd64.deb
      dest: /tmp/filebeat-7.4.0-amd64.deb
  - name: install filebeat deb
    command: dpkg -i /tmp/filebeat-7.4.0-amd64.deb
  - name: drop in filebeat.yml
    copy:
      src: /etc/ansible/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml
  - name: enable and configure system module
    command: filebeat modules enable system
  - name: filebeat setup  
    command: filebeat setup
  - name: filebeat start 
    command: service filebeat start
  - name: enable service filebeat on boot
    systemd:
      name: filebeat
      enabled: yes
